<a href="https://colab.research.google.com/github/ZiaulKarim245/Learn-Pandas/blob/main/Pandas_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating

In [ ]:
import pandas as pd

**DataFrame**

In [ ]:
# Column by Column Method
df1 = pd.DataFrame(
    {"StudentID" : ["C1100039"]}
)
print(df1)

df1 = pd.DataFrame(
    {"StudentID" : "C1100039"},
    index = [0]
)
print(df1)

# Row by Row Method
df1 = pd.DataFrame([
    {"StudentID" : "C1100039"}
])
print(df1)

   StudenID
0  C1100039
   StudenID
0  C1100039
   StudenID
0  C1100039

In [ ]:
# Column by Column Method
df2 = pd.DataFrame({
    'Student' : ['C2211', 'C2222', 'C3333'],
    'Name' : ['A', 'B', 'C'],
    'Marks' : [100, 91, 87]
},
index=[1,2,3])
print(df2)

# Row by Row Method
df2 = pd.DataFrame([
    {'StudentID': 'C2211', 'Name': 'A', 'Marks': 100},
    {'StudentID': 'C1111', 'Name': 'B', 'Marks': 92},
    {'StudentID': 'C3333', 'Name': 'C', 'Marks': 85}
])
print('\n', df2)
df2

  Student Name  Marks
1   C2211    A    100
2   C2222    B     91
3   C3333    C     87

   StudentID Name  Marks
0     C2211    A    100
1     C1111    B     92
2     C3333    C     85

  StudentID Name  Marks
0     C2211    A    100
1     C1111    B     92
2     C3333    C     85

In [ ]:
# Display the first 5 rows to quickly inspect the data format
df2.head()

  StudentID Name  Marks
0     C2211    A    100
1     C1111    B     92
2     C3333    C     85

In [ ]:
# Get the dimensions of the DataFrame (number of rows and columns)
df2.shape
df2.shape[0]

(3, 3)

In [ ]:
# View a summary of data types and check for any missing/null values
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  3 non-null      object
 1   Name       3 non-null      object
 2   Marks      3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df2.to_csv('xyz.csv', index=False)
df2.to_excel('xyz.xlsx')
df2.to_json('xyz.json')

**Series**

In [ ]:
df3 = pd.Series([1,2,3,4,5])
print(df3)

df3 = pd.Series([50, 62, 77], index= ['2024 Sales', '2025 Sales', '2026 Sales'], name='Product A')
print('\n',df3)

0    1
1    2
2    3
3    4
4    5
dtype: int64

 2024 Sales    50
2025 Sales    62
2026 Sales    77
Name: Product A, dtype: int64

# Reading

In [ ]:
df = pd.read_csv("/kaggle/input/wine-reviews/winemag-data_first150k.csv", index_col=0, sep='\t')
df = pd.read_excel("xyz.xlsx")
df = pd.read_json("xyz.json")

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.to_csv('xyz.csv', index=False)
df.to_excel('xyz.xlsx')
df.to_json('xyz.json')

# Indexing & Selection

**Native accessors**

In [ ]:
# Let's take "reviews" as a DataFrame
reviews.country
reviews.country[0]
reviews.country.loc[0]
reviews['country']
reviews['country'][10]
reviews['country'][:10]

**Index-based Selection**

In [ ]:
reviews.iloc[0]
reviews.iloc[:,0]
reviews.iloc[:3,0]
reviews.iloc[[1,2,3],[:5]]
reivews.iloc[-10]
reviews.iloc[-5:,0]

**Label-based selection**

In [ ]:
reviews.loc[0,'country']
reviews.loc[:2, ['tester_name', 'tester_twitter_handle', 'points']]
reviews.loc[[1,2,3], ['tester_name', 'tester_twitter_handle', 'points']]
reviews.loc['country', :5]
# loc range count inclusive => loc[:99] means 100

**Conditional selection**

In [ ]:
reviews.country == 'Italy'
reviews['country'] == 'Italy'
reviews.iloc[:,0] == 'Italy'   # Index Risk
reviews.loc[:,'country'] == 'Italy'
# Return a True/False Series

In [ ]:
reviews.loc[reviews['country'] == 'Italy']
reviews.iloc[reviews.country == 'Italy']  # ValueError

In [ ]:
reviews.loc[(reviews['country'] == 'Italy') & (reviews['points'] >= 90)]
reviews.loc[(reviews['country'] == 'Italy') | (reviews['points'] >= 90)]

In [ ]:
reviews.loc[reviews['country'].isin(['Italy', 'French'])]
reviews.loc[reviews['price'].notnull()]
reviews.loc[reviews['price'].isnull()]
reviews.loc[reviews['description'].str.contains('fruity', na=False)]
reviews.loc[reviews['description'].str.starwith('Vintage', na=False)]
reviews.loc[reviews['description'].str.endwith('fruity', na=False)]

In [ ]:
reviews.loc[(reviews.points / reviews.price).idxmax(), 'title']

# Assigning Data

In [ ]:
reviews['critic'] = 'everyone'
reviews['critic']
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

# Summary Functions

In [ ]:
reviews['points'].describe()
reviews['tester_name'].describe()
reviews.points.mean()
reviews.points.median()
reviews.points.mode()
reviews.tester_name.unique()
reviews['tester_name'].value_counts()

# Maps

In [ ]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda point:point - review_points_mean) # Flexible
reviews.points - review_points_mean # Faster
# Both return a Series
reviews.country + ' - ' + reviews.region_2 # series

In [ ]:
tropical_count = reviews['description'].map(lambda desc: 'tropical' in str(desc)).sum()
fruity_count = reviews['description'].map(lambda desc: 'fruity' in str(desc)).sum()

descriptor_counts = pd.Series([tropical_count, fruity_count], index=['tropical', 'fruity']) # Slower

tropical_count = reviews['description'].str.contains('tropical', na=False).sum()
fruity_count = reviews['description'].str.contains('fruity', na=False).sum()

descriptor_counts = pd.Series([tropical_count, fruity_count], index=['tropical', 'fruity']) # Faster

In [ ]:
def remean_point(row):
  row.points -= review_points_mean
  return row

review.apply(remean_point, axis='columns') # axis=1
# retun copied DataFrame
# .apply() can handle complex logic that .map() can't but both are slow

In [ ]:
def stars(row):
    if row.country == 'canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

star_ratings = reviews.apply(stars, axis=1)

# Grouping

In [ ]:
reviews.groupby('points')['points'].count() # count() => series
reviews.groupby('points').count() # count => dataframe
reviews['points'].value_counts()
reviews.groupby('points').price.min()
reviews.groupby('points')[price].max()
reviews.groupby('points')[price].mean()
reviews.groupby('points')['price'].agg(['min', 'max', 'mean', 'count', 'size'])
reviews.groupby(['country']).price.agg([len, min, max])

In [ ]:
reviewer_mean_ratings = reviews.groupby('taster_name')['points'].mean()

In [ ]:
price_extremes = reviews.groupby('variety')['price'].agg(['min','max'])
price_extremes = reviews.groupby('variety').price.agg([min,max])

In [ ]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0]) # Slow
reviews.groupby('winery')['title'].first()

In [ ]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])
reviews.groupby(['country', 'province'])['points'].idxmax()
reviews.loc[reviews.groupby(['country', 'province']).points.idxmax()]

In [ ]:
reviews_written = reviews.groupby('taster_twitter_handle').size() # size() => series
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()

**Multi-indexes**

In [ ]:
countries_reviewed_1 = reviews.groupby(['country', 'province'])['description'].agg(['len'])  # .len() => X
countries_reviewed_2 = reviews.groupby(['country', 'province']).size()
countries_reviewed_1 = countries_reviewed_1.reset_index()
countries_reviewed_2 = countries_reviewed_2.reset_index(name='size_count')

# Sorting

In [ ]:
countries_reviewed_1.sort_values(by='len')
countries_reviewed_1.sort_values(by='len', ascending=False)
countries_reviewed_2.sort_values(by='size_count')
countries_reviewed_2.sort_values(by=['country', 'size_count'])
countries_reviewed_1.sort_values(by=['country', 'len'], ascending=[True, False])
countries_reviewed_1.sort_index()

In [ ]:
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()

In [ ]:
sorted_varieties = reviews.groupby('variety').price.agg([min,max]).sort_values(by=['min','max'], ascending=[False, False])

In [ ]:
country_variety_counts = reviews.groupby(['country', 'variety']).variety.size().sort_values(ascending=False) # size() => series so 'by' => X

# Data Types

In [ ]:
reviews['price'].dtype
reviews.dtypes
reviews.points.astype('float64')
reviews.index.dtype

# Missing Values

In [ ]:
pd.isnull(reviews.country)
reviews.country.isnull()
pd.notnull(reviews.country)
reviews.country.notnull()
reviews[pd.isnull(reviews.country)]
reviews[reviews.country.isnull()]
reviews[pd.notnull(reviews.country)]
reviews[reviews.country.notnull()]
reviews.isnull()
reviews.notnull()

In [ ]:
reviews.isnull().sum()
reviews.notnull().sum()
reviews.description.isnull().sum()
reviews.isnull().mean()*100

In [ ]:
reviews.fillna('Unknown') # Risky => int -> str
reviews['description'].fillna('Unknown')

In [ ]:
reviews.region_1 = reviews.region_1.fillna('Unknown')
reviews_per_region = reviews.region_1.value_counts().sort_values(ascending=False)

reviews_per_region = reviews.groupby('region_1').size().sort_values(ascending=False)  # size() => series but count() => dataframe

In [ ]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

In [ ]:
reviews.region_2 = reviews.region_2.fillna('Unknown')

reviews.taster_twitter_handle = reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")